### ISSUE TITLE
[Bug] Error parsing JSON in message_data in fivetran_log__connector_status 

### ISSUE THREAD

**Issue by andysteinitz** [fivetran/dbt_fivetran_log#46] opened 2022-04-04 22:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Starting with `fivetran_log` package version 0.5.1 on Snowflake the macro `fivetran_utils.json_parse` replaces `json_extract_path_text(try_parse_json( message_data ), 'status' )` with ` parse_json( message_data )['status']`. 
This is causing the model  `fivetran_log__connector_status` to fail on our data with "Error parsing JSON: unknown keyword" when querying the field message_data for an old transform event.

These old events were created using fivetran_log version 0.1.0.
In our raw data (`raw.fivetran_log.log`) an example of this message_data is `skipper_breech(myorg/Warehouse/engagement_snapshot) run=37036084 Transformation run has succeeded. Result: The transformation has completed successfully.` 

`try_parse_json(message_data)` is null for these records. All of these raw log events have `id = 'skipper_breech'`

### Relevant error log or model output

When running the cte `connector_log` in `fivetran_log__connector_status`

```shell
with connector_log as (

    select *,
        sum( case when event_subtype in ('sync_start') then 1 else 0 end) over ( partition by connector_id 
            order by created_at rows unbounded preceding) as sync_batch_id
    from transformed.dev_asteinitz.stg_fivetran_log__log

    -- only looking at errors, warnings, and syncs here
    where event_type = 'SEVERE'
        or event_type = 'WARNING'
        or event_subtype like 'sync%'
        or (event_subtype = 'status' 
            and 

  parse_json( message_data )['status'] = 'RESCHEDULED'
            
            and 

  parse_json( message_data )['reason'] like '%intended behavior%'
            ) -- for priority-first syncs. these should be captured by event_type = 'WARNING' but let's make sure
        or (event_subtype = 'status' 
            and 

  parse_json( message_data )['status'] = 'SUCCESSFUL'
        )
        -- whole reason is "We have rescheduled the connector to force flush data from the forward sync into your destination. This is intended behavior and means that the connector is working as expected."
)
select * from connector_log
```
the output is `Error parsing JSON: unknown keyword "skipper_breech", pos 15`

### Expected behavior

the package would continue to use `try_parse_json` instead of assuming the json is valid and apply `parse_json`

### dbt Project configurations

vars:
    fivetran_log:
        fivetran_log_database: RAW
        fivetran_log_schema: FIVETRAN_LOG
        fivetran_log_using_transformations: false # this will disable all transformation + trigger_table logic
        fivetran_log_using_triggers: false # this will disable only trigger_table logic 

### Package versions

packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.1
  - package: fivetran/fivetran_log
    version: 0.5.0
  - package: dbt-labs/audit_helper
    version: 0.5.0

### What database are you using dbt with?

snowflake

### dbt Version

dbt 1.0.4

### Additional Context

An example of this type of event is in [stg_fivetran_log__log-sample.csv](https://github.com/fivetran/dbt_fivetran_log/files/8413434/stg_fivetran_log__log-sample.csv) the entry with `log_id = skipper_breech` is problematic. The other two parse ok (see last column).

Currently installed 0.5.0 version of `fivetran_log__connector_status` that works
![image](https://user-images.githubusercontent.com/7853146/161641135-0b04f9e2-6265-4efa-8926-60cf6ea39ce8.png)

Newer 0.5.1 version that fails
![image](https://user-images.githubusercontent.com/7853146/161641238-7efc25d2-8ed2-4fdf-8b77-1c74b08557d7.png)

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment] 2022-04-05 16:04
@rcaddell and @andysteinitz Thanks for being part of this conversation to help and resolve the issue you are seeing on your end. Unfortunately, my work computer died this week 😢  and I am unable to effectively debug these issues. However, I have been able to do some digging and believe I have narrowed the issue to just the Transformation logs.

Would you be able to try out my draft branch which filters our all transformation records and let me know if you still see the JSON error. You can install the branch using the below in your `packages.yml`
```yml
packages:
    - git: https://github.com/fivetran/dbt_fivetran_log.git
      revision: fivetran-joemarkiewicz-patch-1
      warn-unpinned: false
```

Let me know if you have any success!

**Comment by rcaddell** [comment] 2022-04-05 16:16
@fivetran-joemarkiewicz , just ran and it reintroduces #42

>Failure in test dbt_utils_unique_combination_of_columns_fivetran_log__schema_changelog_connector_id__destination_id__created_at (models/fivetran_log.yml)

**Comment by fivetran-joemarkiewicz** [comment] 2022-04-05 18:17
@rcaddell what version of the package are you using?

**Comment by rcaddell** [comment] 2022-04-05 18:20
@fivetran-joemarkiewicz I am using your revision:

fivetran-joemarkiewicz-patch-1

**Comment by fivetran-joemarkiewicz** [comment] 2022-04-05 18:22
Ah gotchya my bad, I knew that 🤦 

Would you be able to share one of the records where this uniqueness test is failing for you? As a result of #42 the `log_id` should have been updated the the truly unique record instead of just the `connector_id`. I am curious if after a resync did the IDs not update for you?

**Comment by fivetran-joemarkiewicz** [comment] 2022-04-05 19:25
> @rcaddell and @andysteinitz Thanks for being part of this conversation to help and resolve the issue you are seeing on your end. Unfortunately, my work computer died this week 😢 and I am unable to effectively debug these issues. However, I have been able to do some digging and believe I have narrowed the issue to just the Transformation logs.
> 
> Would you be able to try out my draft branch which filters our all transformation records and let me know if you still see the JSON error. You can install the branch using the below in your `packages.yml`
> 
> ```yaml
> packages:
>     - git: https://github.com/fivetran/dbt_fivetran_log.git
>       revision: fivetran-joemarkiewicz-patch-1
>       warn-unpinned: false
> ```
> 
> Let me know if you have any success!

@andysteinitz I would be curious what the results are for you with this branch when you have a chance. 🤔

**Comment by rcaddell** [comment] 2022-04-05 19:53
@fivetran-joemarkiewicz, attached 
[schema_changelog.csv](https://github.com/fivetran/dbt_fivetran_log/files/8421434/schema_changelog.csv)
[validation_errors.csv](https://github.com/fivetran/dbt_fivetran_log/files/8421435/validation_errors.csv)

**Comment by fivetran-joemarkiewicz** [comment] 2022-04-05 20:00
@rcaddell thanks so much for sharing this additional information! 

Unfortunately for those remaining errors I think it would be best to open a [Support Ticket](https://support.fivetran.com/hc/en-us/categories/360006232653-Troubleshooting) as I believe, after looking at the output logs you provided, these duplicates may be arising from an underlying issue within the connector.

**Comment by andysteinitz** [comment] 2022-04-06 21:04
@fivetran-joemarkiewicz your git revision completed successfully for my instance.

**Comment by fivetran-joemarkiewicz** [comment] 2022-04-06 21:41
Thanks @andysteinitz that leads me to believe that the root cause of the original issue is within the Transformations logs. 

The working branch I have is a simple hard code fix that removes the transformation logs, but I will spend some more time over the next week implementing a more permanent solution. Feel free to use this branch for the time being, but I will let you know once a new branch is available for you to test before we include it in the next release of the package.

Thanks again!

**Comment by fivetran-joemarkiewicz** [comment] 2022-04-18 19:45
Hi All,

The above PR is open for review and I hope we will be able to get a release out early this week. In the meantime, feel free to test out the changes within the following branch.
```yml
packages:
  - git: https://github.com/fivetran/dbt_fivetran_log.git
    revision: bugfix/transformation-log-and-changelog-test
    warn-unpinned: false
```
This branch fixes a schema test within the `fivetran_log__schema_changelog` model as well as filtering out transformation logs within the `fivetran_log__connector_status models`. 

Let me know if you have any questions and I hope we will be able to cut a release with these updates soon!

**Comment by fivetran-joemarkiewicz** [comment] 2022-04-20 18:17
Hi All! 

I sincerely appreciate your patience while we developed the adjustments within the package to account for the bug mentioned in this ticket. I was just able to cut the latest release of the dbt_fivetran_log `v0.5.4` package which applies a bugfix to account for the issue detailed in this ticket.

The `v0.5.4` release should be live on the dbt hub at the top of the hour. I will be closing this issue as the latest release should resolve this issue. Please feel free to comment in this issue, or open a new one, if you encounter any questions in the latest release.

Thanks for all your help in identifying and resolving this issue! 🎉

**Closed by fivetran-joemarkiewicz** 2022-04-20 18:17 UTC
Labels: bug
